apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-converter-config
  namespace: pdf-converter
data:
  #VALKEY_HOST: "my-valkey-cluster.default.svc.cluster.local"
  VALKEY_HOST: "valkey"
  VALKEY_PORT: "6379"
  MINIO_HOST: "myminio-hl.minio-tenant.svc.cluster.local:9000"
  BUCKET: "documentos"
  STREAM: "trabajos"
  PYTHONUNBUFFERED: "1"