apiVersion: v1
kind: Secret
metadata:
  name: pdf-converter-secrets
  namespace: pdf-converter
type: Opaque
stringData:
  MINIO_ACCESS_KEY: #MINIO_ACCESS_KEY
  MINIO_SECRET_KEY: #MINIO_SECRET_KEY
  VALKEY_PASSWORD: #VALKEY_PASSWORD
