apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pdf-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: triniperea/pdf-converter-backend:latest  
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: pdf-converter-config
        - secretRef:
            name: pdf-converter-secrets
