server {
    listen 80;

    # Servir archivos estáticos del Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy al Backend para HTTP
    location /api/ {
        proxy_pass http://backend.pdf-converter.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy al Backend para WebSocket
    location /ws/ {
        proxy_pass http://backend.pdf-converter.svc.cluster.local/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}